apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: producer-topic1-binding
  namespace: default
spec:
  instanceRef:
    name: topic1
  parameters:
    serviceAccount: User:118651
